### ISSUE TITLE
Using decorators

### ISSUE THREAD

**Issue by gvocale** [storybookjs/ember-cli-storybook#18] opened 2019-10-31 17:29 UTC
Is it possible to use `decorators` with Storybook for Ember?

Something like this doesn't seem to work:
```
export default {
  title: 'Component name',
  decorators: [storyFn => <div style={{ backgroundColor: 'yellow' }}>{storyFn()}</div>],
};
```

It returns:
```
Module parse failed: Unexpected token (108:11)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
 * ./node_modules/@storybook/source-loader/dist/server/index.js
You may need an additional loader to handle the result of these loaders.
|   },
|   decorators: [function (storyFn) {
>     return <div style={{
|       backgroundColor: 'yellow'
|     }}>{storyFn()}</div>;
 @ ./.storybook/config.js 35:281-337
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=true
```

**Comment by dbendaou** [comment] 2019-11-18 16:10
Try something like this : 
```javascript
export const YOUR_STORY_NAME = () => ({
  template: hbs`...something....`,
});

**Comment by arthur5005** [comment] 2019-11-21 00:10
@dbendaou can you more complete example. I'm having the same problem, I feel like the JSX isn't parsing properly (as if it's not meant to)

A

**Comment by dbendaou** [comment] 2019-11-21 13:53
yup ! Will update the ember doc once I've time ! In the meantime, you can try this :

**Comment by dbendaou** [comment] 2019-11-21 14:09
BTW, you have to import hbs in order to compile properly, JSX is for react :) 

`import hbs from 'htmlbars-inline-precompile';`

**Comment by gvocale** [comment] 2019-11-21 16:49
How to add instead a decorator like `Center` of the example on https://storybook.js.org/docs/addons/introduction/

I tried the following:
```
const styles = {
  textAlign: 'center',
};
const Center = ({ children }) => <div style={styles}>{children}</div>;

YOUR_STORY_NAME.story = {
  decorators: Center
};
```
But I get this error:
```
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| var Center = function Center(_ref2) {
|   var children = _ref2.children;
>   return <div style={styles}>{children}</div>;
| };
```

**Comment by arthur5005** [comment] 2019-11-22 02:35
> BTW, you have to import hbs in order to compile properly, JSX is for react :)
> 
> `import hbs from 'htmlbars-inline-precompile';`

For sure, I get what you're saying! And I understand that JSX is for React.

I've got my stories working with the hbs` string literal just fine.

It's when I want to create a _custom_ decorator, that I run into problems. 

This is especially handy for adding at the config level, and wanting to wrap all stories with some sort of element with style, margins or class.

All examples use JSX syntax, providing an arrow function, where a `storyFn()` callback is passed in, so that you can place your story anywhere you want in the JSX template. 

I have no idea how to translate this into a decorator for this framework.

**Comment by dbendaou** [comment] 2019-11-25 08:56
You can use `centered` decorators this way 
```js
import hbs from 'htmlbars-inline-precompile';
import Centered from '@storybook/addon-centered/ember';

export default {
  decorators: [Centered],

  parameters: {
    component: Centered,
  },
};
```

**Comment by gvocale** [comment] 2019-11-25 12:20
Thank you for your answer. My question is more about how can I create my own wrapper around a story. For example I would add some padding and other styling. For example:

```
const MyOwnWrapper = ({ children }) => <div style="padding: 24px; display: grid; .... "><div style="...">{children}</div></div>;
```

With JSX would be pretty easy, but for Ember, how can I add some extra divs and styling around each story?

**Comment by meirish** [comment] 2019-12-04 03:46
If you need to do additional DOM manipulation in a decorator, Ember stories can have a third argument, `element` that is used in the [render method](https://github.com/storybookjs/storybook/blob/21b8a7fb2ca2ace85be14accabc5e046f9189377/app/ember/src/client/preview/render.js#L40-L45) in storybook. Here's an example: https://github.com/hashicorp/vault/blob/967b8c96f77ca2a672b5ec99d3ea6c904fd79d83/ui/.storybook/config.js#L18-L47 

Hope this clarifies things!

**Comment by gvocale** [comment] 2020-01-28 20:21
@meirish can you please give me an example on how to use it in a single story?
I'm trying the following, but I get `TypeError: Cannot read property 'name' of undefined`:

```
ComponentName.story = {
  decorators: [addSpace],
};

const addSpace = (storyFn) => {
  const { template, context } = storyFn();

  // This adds styling to the Canvas tab.
  const styles = {
    style: {
      margin: '20px',
    },
  };

  // Create a div to wrap the Canvas tab with the applied styles.
  const element = document.createElement('div');
  Object.assign(element.style, styles.style);

  const innerElement = document.createElement('div');
  const wormhole = document.createElement('div');
  wormhole.setAttribute('id', 'ember-basic-dropdown-wormhole');
  innerElement.appendChild(wormhole);

  element.appendChild(innerElement);
  innerElement.appendTo = function appendTo(el) {
    el.appendChild(element);
  };

  return {
    template,
    context,
    element: innerElement,
  };
};

**Comment by dbendaou** [comment] 2020-07-01 09:21
@gvocale that's because you should declare your decorator before linking it to your component's story. 
Try to add 
```
ComponentName.story = {
  decorators: [addSpace],
};
```
after the decorator instead !

**Comment by dbendaou** [comment] 2020-07-01 16:28
If the issue is now resolve could you close it @gvocale ? 😊

**Comment by gabrielcsapo** [comment] 2020-07-01 17:44
Thanks for everyones helping in solving this!

**Closed by gabrielcsapo** 2020-07-01 17:44 UTC
